### ISSUE TITLE
Práctica 1 proposiciones 

### ISSUE THREAD

**Issue by 23620126** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-23620126#1]
[practica 1 matematicas discretas(1).docx](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-23620126/files/13194215/practica.1.matematicas.discretas.1.docx)

**Comment by NBbrook** [comment]
portada: 25/25
procedimiento: 20/25, (no hay objetivo ni descripción de actividades)
figuras: 22/25 (no hay procedimiento)
resultados: 25/25 
total: 18.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
